language: node_js
node_js:
- 9
- 8
- 7
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn dev
- yarn lint
notifications:
  slack:
    on_success: change
    rooms:
      - secure: "q/C2HMAnUnm/Nr+8ZRQVhBmSac6hoLBHdWsJyhDOI5WMCTToxIMd7rss5fLCyFxyaahklYmhrkn4WNaXI+D39ba8yxmyitbh364NkZrJKUT8zm6k80QLVvC76f4fhoKZszhkgOXD/QB/gpCi9/ELHXUXBE2ynmq6uKj7GlbuLLraXzWn3uPfb2pFx14+58y9cnGliZQQj3b1eX4JKqrPAOND/uOV04N2g7JxfEWV1xusUdVy4QvaNR1PfKAeoEg6ZL/QSBkSc84p2f/0d/c0EkdT7oMc59YgOO22cUcW4MrIsptU+T+VgklWN044EVoExD7lbZo473y1CVvEkOtw2V/5s+tPCyCy3Hj+WBXpHcgQLZYX4hXcbhsYQ78Ov6gkBMBzAV7/10PAynQBbI4unRNLszFthz0fDhboiCYoyW1AeMiVuoN9FZHL3+3ah7HrG+QckOA3gHH0Fn2rc8NartX1vUa6X7n+1CtPg2z2fCYnHJ/uiGXw+g9pdaIOpm6fY2UzFhCjJuN4GQXrChR8NCR/oQmhJmuRT5upk9vgN13vpkdF0XFtQU+I6/JWoQAfZ79xhTrK5Y2pNQY5Ytbq1AKm68m+9O1jsQ/jDZpYwBZVHgJJBHU4AurdFZxZJWduc47ligPzHhXtTNFUtjaXuBY8/gA1KqrIa85j8r8BSws="
